spring:
  application:
            name: secure-public-rest-api-mobile-web-application
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://secure


server:
  port: 8081
